

let stockHardware = [

    {id: 1, nombre: "CAFE SALVADOREÑO",  tipo: "Molienda fina", cantidad: 1, desc: "Sabor suave", precio: 34000, marca: "503SV", img: './img/sv1.jpg'},
    {id: 2, nombre: "CAFE SALVADOREÑO",  tipo: "Molienda fina", cantidad: 1, desc: "Sabor medio", precio: 34000, marca: "503SV", img: './img/sv2.jpg'},
    {id: 3, nombre: "CAFE SALVADOREÑO",  tipo: "Molienda fina", cantidad: 1, desc: "Sabor medio alto", precio: 34000, marca: "503SV", img: './img/sv3.jpg'},
    {id: 4, nombre: "CAFE SALVADOREÑO",  tipo: "Molienda fina", cantidad: 1, desc: "Sabor fuerte", precio: 34000, marca: "503SV", img: './img/sv4.jpg'},
    {id: 5, nombre: "CAFE SALVADOREÑO",  tipo: "Molienda fina", cantidad: 1, desc: "Sabor muy fuerte", precio: 34000, marca: "503SV", img: './img/sv8.jpg'},

]